FROM python:3.12-slim

# Создаём рабочую директорию
WORKDIR /app

# Копируем все нужные файлы
COPY . .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Указываем порт приложения
EXPOSE 5000


# Запускаем приложение с помощью uvicorn, делая его доступным по сети
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"] 
